rootProject.name = 'mi-proyecto-karate'
plugins {
    id 'java'
}

group = 'com.tuempresa'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'com.intuit.karate:karate-junit5:1.4.1'
}

test {
    useJUnitPlatform()
    systemProperty 'karate.options', System.properties.getProperty('karate.options')
    systemProperty 'karate.env', System.properties.getProperty('karate.env')
    outputs.upToDateWhen { false }
}

sourceSets {
    test {
        resources {
            srcDir 'src/test/java'
        }
    }
}